### PR TITLE
n must be bigger than list length to return a none

### PR DESCRIPTION
**Pull request by snowiow**

### CODE REVIEW

**Comment by pheymann** [comment]
Hi, 
thanks for the PR. I just realised that the code can be reduced to:

```scala
list.drop(n).headOption
```

**Comment by snowiow** [comment]
Yes, you are right. Should it be changed in this PR?

**Comment by pheymann** [comment]
👍 , just make sure you pull the latest changes. Right now we see a merge conflict.

**Comment by snowiow** [comment]
ok done :+1:

**Pull request merged**
