### PR TITLE
FP functions: total, deterministic, pure

### PR DESCRIPTION
**Pull request by philipschwarz**
Hello, just a suggestion: instead of defining pure functions as you do, how about defining FP functions as total, deterministic and pure, as is done here: https://twitter.com/jdegoes/status/936301872066977792.
Or as total, deterministic and Inculpable, as is done here: https://github.com/fommil/fpmortals/blob/master/manuscript/introduction.md

I have only edited the slide to draw attention to the above potential improvement, I am not suggesting that you merge the changes I have made.

### CODE REVIEW

**Comment by pheymann** [comment]
Hi @philipschwarz ,
thanks for the input. We appreciate it. Regarding your request, I agree our definition could be a bit more precise. I would just take John's definition because it is quite concise and fits on a slide pretty well.

**Comment by philipschwarz** [comment]
Great! thanks for listening.

**Comment by pheymann** [comment]
I will close this PR and add the changes probably tomorrow. 👍

**Comment by pheymann** [comment]
Now I will definitely apply this change :). Hadn't enough time recently.

**Pull request closed without merging**
